CleanDesk/Controllers/HomeController.cs
using CleanDesk.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CleanDesk.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("EmployeeId") != null)
                {
                    ViewBag.ManagementName = (string)HttpContext.Session.GetString("ManagementName");
                    ViewBag.EmployeeName = (string)HttpContext.Session.GetString("EmployeeName");
                    ViewBag.EmployeeType = (int)HttpContext.Session.GetInt32("EmployeeTypeId");

                    return View();
                }

                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = ex.Message.ToString() });
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(string errorMessage)
        {
            ViewBag.ErrorMessage = errorMessage;
            return View();
        }
    }
}

CleanDesk/Controllers/ReportController.cs
using CleanDesk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static CleanDesk.Core.Interfaces;

namespace CleanDesk.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReport _report;
        private readonly IRequest _request;
        public ReportController(IReport report, IRequest request)
        {
            this._report = report;
            this._request = request;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllRequestsDetailQueue()
        {
            try
            {
                if (HttpContext.Session.GetString("EmployeeId") != null)
                {
                    ViewBag.ManagementName = (string)HttpContext.Session.GetString("ManagementName");
                    ViewBag.EmployeeName = (string)HttpContext.Session.GetString("EmployeeName");

                    List<RequestDetailModel> model = _report.GetAllRequestsDetailQueue();

                    return View(model);
                }

                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = ex.Message.ToString() });
            }
        }

        public IActionResult AllResolveRequestsDetailQueue()
        {
            try
            {
                if (HttpContext.Session.GetString("EmployeeId") != null)
                {
                    ViewBag.ManagementName = (string)HttpContext.Session.GetString("ManagementName");
                    ViewBag.EmployeeName = (string)HttpContext.Session.GetString("EmployeeName");

                    List<RequestDetailModel> model = _report.GetResolveRequestsDetailQueue();

                    return View(model);
                }

                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = ex.Message.ToString() });
            }
        }

        public IActionResult AllUnresolveRequestsDetailQueue()
        {
            try
            {
                if (HttpContext.Session.GetString("EmployeeId") != null)
                {
                    ViewBag.ManagementName = (string)HttpContext.Session.GetString("ManagementName");
                    ViewBag.EmployeeName = (string)HttpContext.Session.GetString("EmployeeName");

                    List<RequestDetailModel> model = _report.GetUnresolveRequestsDetailQueue();

                    return View(model);
                }

                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = ex.Message.ToString() });
            }
        }


        public IActionResult TechRequestObservationsDetail(int requestId, string techName)
        {
            try
            {
                if (HttpContext.Session.GetString("EmployeeId") != null)
                {
                    int employeeId = 0;

                    RequestDetailModel model = new()
                    {
                        RequestId = requestId,
                        TechnicianName = techName
                    };

                    var request = _request.GetAllById(requestId);

                    foreach (var item in request)
                    {
                        ViewBag.EmployeeRequestName = item.EmployeeName;
                        ViewBag.RequestDescription = item.RequestDescription;
                        ViewBag.LocationName = item.LocationName;
                        ViewBag.FloorNumber = item.FloorNumber;
                        ViewBag.ExtensionNumber = item.ExtensionNumber;
                        ViewBag.RequestDate = item.RequestDate;
                        ViewBag.IPNumber = item.IPNumber;
                        ViewBag.Management = item.ManagementName;
                        employeeId = item.EmployeeId;
                    }

                    ViewBag.ManagementName = (string)HttpContext.Session.GetString("ManagementName");
                    ViewBag.EmployeeName = (string)HttpContext.Session.GetString("EmployeeName");
                    ViewBag.EmployeeId = (int)HttpContext.Session.GetInt32("EmployeeId");
                    ViewBag.RequestDetailList = _request.GetAllDetailsByRequestId(requestId);

                    return View(model);
                }
            }

            catch (Exception)
            {

                throw;
            }

            return View();
        }
        public IActionResult SelectRequest(int requestId, string techName)
        {
            var employeeId = HttpContext.Session.GetInt32("EmployeeId");

            try
            {
                if (ModelState.IsValid)
                {
                    RequestDetailModel model = new()
                    {
                        RequestId = requestId,
                        EmployeeId = (int)employeeId
                    };

                    return RedirectToAction("TechRequestObservationsDetail", new { requestId, techName });
                }

                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = ex.Message.ToString() });
            }
        }
    }
}

CleanDesk/Views/Home/Index.cshtml
@{
	Layout = "";    
}
<!DOCTYPE HTML>
<html>
	<head>
		<title>SoporteTecnico - Home</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="~/assets/css/main.css" />
		<noscript><link rel="stylesheet" href="~/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">
								<!-- Logo -->
								<a href="#" class="logo">
									<span class="symbol"><img src="~/images/logo_login.jpg" alt="" /></span>
									<span class="title">SoporteTecnico</span>
									<br />
									<span class="title">Gerencia de Tecnología</span>
								</a>	
						</div>
						<!-- Nav -->
							<nav>
								<ul>
									<li><a href="#menu">Menu</a></li>
								</ul>
							</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li>@Html.ActionLink("Salir", "Login", "Login")</li>
						</ul>
					</nav>	
					
				<!-- Main -->
					<div id="main">
						<div class="inner">
							<header>				
								<h1>Hola @ViewBag.EmployeeName bienvenid@@ al sistema de atención al usuario, selecciona que deseas hacer</h1>
							</header>
							<section class="tiles">
								@{
									if(ViewBag.EmployeeType == 2)
									{
										<article class="style3">
											<span class="image">
												<img src="~/images/image7.jpg" alt="" />
											</span>
												@Html.ActionLink("Seleccionar solicitud de la cola","RequestQueue","Request")
										</article>
										<article class="style4">
											<span class="image">
												<img src="~/images/image8.jpg" alt="" />
											</span>
												@Html.ActionLink("Solicitudes que estoy atendiendo","RequestDetailQueue","Request")
										</article>
									}
								}

								@{
									if(ViewBag.EmployeeType == 3)
									{
										<article class="style3">
											<span class="image">
												<img src="~/images/image7.jpg" alt="" />
											</span>
												@Html.ActionLink("Consultar solicitudes en cola","RequestQueue","Request")
										</article>
										<article class="style4">
											<span class="image">
												<img src="~/images/image8.jpg" alt="" />
											</span>
												@Html.ActionLink("Solicitudes en atención (todos)","RequestDetailQueue","Request")
										</article>
										<article class="style1">
											<span class="image">
												<img src="~/images/image3.jpg" alt="" />
											</span>	
											@Html.ActionLink("Generar solicitud","Add","Request")
										</article>
										<article class="style2">
											<span class="image">
												<img src="~/images/image4.jpg" alt="" />
											</span>
												@Html.ActionLink("Consultar estado de tus solicitudes","RequestUserDetailQueue","Request")
										</article>
										<article class="style5">
											<span class="image">
												<img src="~/images/image5.jpg" alt="" />
											</span>
												@Html.ActionLink("Consultas generales","Index","Report")
										</article>
									}
								}

								@{
									if(ViewBag.EmployeeType == 1)
									{
										<article class="style1">
											<span class="image">
												<img src="~/images/image3.jpg" alt="" />
											</span>	
											@Html.ActionLink("Generar solicitud","Add","Request")
										</article>
										<article class="style2">
											<span class="image">
												<img src="~/images/image4.jpg" alt="" />
											</span>
												@Html.ActionLink("Consultar estado de tus solicitudes","RequestUserDetailQueue","Request")
										</article>
									}
								}
							</section>
						</div>
					</div>
			</div>

		<!-- Scripts -->
			<script src="~/assets/js/jquery.min.js"></script>
			<script src="~/assets/js/browser.min.js"></script>
			<script src="~/assets/js/breakpoints.min.js"></script>
			<script src="~/assets/js/util.js"></script>
			<script src="~/assets/js/main.js"></script>
	</body>
</html>